# Travel Log - Portainer Stack
#
# Deploy this in Portainer under Stacks > Add Stack > Web editor
#
# REQUIRED: Set the following environment variables in Portainer's
# "Environment variables" section before deploying:
#
#   GEMINI_API_KEY   - Your Google Gemini API key (free at https://aistudio.google.com/app/apikey)
#   POSTGRES_PASSWORD - A strong password for the database (e.g. changeme123)
#
# OPTIONAL:
#   APP_PORT         - Host port to expose the app on (default: 3000)
#   OPENAI_API_KEY   - OpenAI API key (alternative to Gemini)

version: '3.8'

services:
  travel-log:
    image: ghcr.io/henkdepotvisit/travellog:latest
    container_name: travel-log
    restart: unless-stopped
    ports:
      - "${APP_PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATA_DIR=/app/data
      - DATABASE_URL=postgresql://travellog:${POSTGRES_PASSWORD:-travellog}@travel-log-db:5432/travellog
      - GEMINI_API_KEY=${GEMINI_API_KEY:-}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    volumes:
      - travel_log_data:/app/data
    networks:
      - travel-log-net
    depends_on:
      travel-log-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  travel-log-db:
    image: postgres:16-alpine
    container_name: travel-log-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=travellog
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-travellog}
      - POSTGRES_DB=travellog
    volumes:
      - travel_log_postgres:/var/lib/postgresql/data
    networks:
      - travel-log-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U travellog"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  travel_log_data:
    driver: local
  travel_log_postgres:
    driver: local

networks:
  travel-log-net:
    driver: bridge
